//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezzClass0._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MezClassEntities : DbContext
    {
        public MezClassEntities()
            : base("name=MezClassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Recursos> Recursos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TParametro> TParametro { get; set; }
        public virtual DbSet<TProblema> TProblema { get; set; }
        public virtual DbSet<TProblemaParametro> TProblemaParametro { get; set; }
        public virtual DbSet<TProblemaUsuario> TProblemaUsuario { get; set; }
        public virtual DbSet<TUniverso> TUniverso { get; set; }
    }
}
