//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezzClass0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recursos
    {
        public int IdRecurso { get; set; }
        public int IdProblema { get; set; }
        public string Tipo { get; set; }
        public byte[] Recurso { get; set; }
    
        public virtual TProblema TProblema { get; set; }
    }
}
