//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezzClass0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TParametro
    {
        public TParametro()
        {
            this.TProblemaParametro = new HashSet<TProblemaParametro>();
        }
    
        public int IdParametro { get; set; }
        public string NombParametro { get; set; }
        public string descripcion { get; set; }
        public int Peso { get; set; }
        public int IdUniverso { get; set; }
    
        public virtual TUniverso TUniverso { get; set; }
        public virtual ICollection<TProblemaParametro> TProblemaParametro { get; set; }
    }
}
