//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezzClass0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProblemaParametro
    {
        public int IdProblema { get; set; }
        public int IdParametro { get; set; }
        public Nullable<double> Valor { get; set; }
        public int id { get; set; }
    
        public virtual TParametro TParametro { get; set; }
        public virtual TProblema TProblema { get; set; }
    }
}
