//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezzClass0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProblema
    {
        public TProblema()
        {
            this.Recursos = new HashSet<Recursos>();
            this.TProblemaParametro = new HashSet<TProblemaParametro>();
            this.TProblemaUsuario = new HashSet<TProblemaUsuario>();
        }
    
        public int IdProblema { get; set; }
        public string titulo { get; set; }
        public string Enunciado { get; set; }
        public string Solucion { get; set; }
        public int IdUniverso { get; set; }
        public bool ejemplo { get; set; }
        public int ComplejidadId { get; set; }
        public string usuario { get; set; }
    
        public virtual ICollection<Recursos> Recursos { get; set; }
        public virtual TUniverso TUniverso { get; set; }
        public virtual ICollection<TProblemaParametro> TProblemaParametro { get; set; }
        public virtual ICollection<TProblemaUsuario> TProblemaUsuario { get; set; }
    }
}
