//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezzClass0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUniverso
    {
        public TUniverso()
        {
            this.TParametro = new HashSet<TParametro>();
            this.TProblema = new HashSet<TProblema>();
        }
    
        public int IdUniverso { get; set; }
        public string NombUniverso { get; set; }
        public int CantNiveles { get; set; }
    
        public virtual ICollection<TParametro> TParametro { get; set; }
        public virtual ICollection<TProblema> TProblema { get; set; }
    }
}
